### ISSUE TITLE
GUI Error MAC OS - Text in Dark mode

### ISSUE THREAD

**Issue by KanishkaS** [QIB-Sheffield/WEASEL#24]
Kanishkas-MacBook-Air:WEASEL-master kanishkasharma$ python Weasel.py

Warning: QApplication was created before pyqtgraph was imported; there may be problems (to avoid bugs, call QApplication.setGraphicsSystem("raster") before the QApplication is created).

Error in WriteXMLfromDICOM.open_dicom_to_xml: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

Error in WriteXMLfromDICOM.create_XML_file: 'NoneType' object has no attribute 'iter'

XML file creation time = 1.8169419765472412

Error in TreeView.makeDICOMStudiesTreeView at line 122: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by JSousa-UoL** [comment]
Note for self: there's a similar issue with GUI visualisation in Linux. This error reported may be because of how the selected folder is parsed to Weasel. I will investigate this in a Mac Virtual Machine when possible

**Comment by JSousa-UoL** [comment]
This issue should be solved now @KanishkaS. It wasn't Mac related, it was Python 3.9 - XML.Element.getchildren was deprecated and it's now XML.Element.iter. Please test this on your Python 3.9 on your Mac when possible please.

**Comment by KanishkaS** [comment]
Thanks @JSousa-UoL. The GUI works with DICOM import now for python 3.9.1. 

Only a user interface comment (see below) - it is difficult to view white text on the GUI display at the moment. 
![Screenshot 2021-02-10 at 09 48 25](https://user-images.githubusercontent.com/42036722/107464135-9a640280-6b85-11eb-94af-3520e5863d2d.png)

Thanks!

**Comment by KanishkaS** [comment]
This GUI 'text' issue does not happen when using python 3.8.5.

**Comment by JSousa-UoL** [comment]
Thank you for your feedback @KanishkaS. That's a "funny" one, I wonder why that happens between different Python versions. At first I would say it's because of your Mac's dark mode, but it doesn't seem to be it. Thank you for sharing the requirements.txt and setup.py you used. 

Be very careful with having Anaconda and "normal" Python installed in your Mac. Sometimes that recipe for trouble.

**Comment by JSousa-UoL** [comment]
This white text doesn't seem to be related with Python version. I tested 3.9 and it worked, however the white text shows up when I switched to dark mode.

@IMI-TRISTAN , this is not urgent but I can try to have a look at this. If we want the text to be black in any circumstance, should that be set in styleSheet.py?

**Comment by IMI-TRISTAN** [comment]
Text colour is best specified in styleSheet.py using CSS.  You'd need to
know which widget is displaying the text you wish to change; e.g., QLabel,
QPushButton etc
Steve

**Comment by JSousa-UoL** [comment]
Ok, thanks for the info Steve. I'll keep this issue open and have a look at this when I have the time

**Comment by IMI-TRISTAN** [comment]
Sounds good, thanks!

**Comment by JSousa-UoL** [comment]
This should have been solved now @KanishkaS. Please try to use Weasel in Dark Mode and check if the text in the TreeView is now black. It might not be all perfect in terms of colour/layout, but if it solved the white text for now, we can close. If something else comes up, we'll open a new issue

**Comment by KanishkaS** [comment]
@JSousa-UoL: I did not have the issue on python 3.8.5 (my current version on Mac). This issue was present on python version  3.9 - irrespective or dark/light mode. I cannot test this at the moment as I cannot upgrade my python version at the moment.

**Comment by JSousa-UoL** [comment]
Ok, I'll close this regardless as it's working o my Mac VM Python 3.9. At least we're aware of the Dark Mode in Mac

**Comment by KanishkaS** [comment]
I had to uninstall anaconda as the pip install for weasel created duplicate libraries and caused errors in opening certain applications. This reverted back my python version to 3.9.1. I'm sharing a screenshot - some of the text is still too small to read on the GUI. This is no longer a bur but rather enhancement

**Comment by KanishkaS** [comment]
Also, there is black text on black/grey screen..
![Screenshot 2021-02-18 at 13 01 27](https://user-images.githubusercontent.com/42036722/108320981-85244f00-71e9-11eb-8f5a-4aac4975b03f.png)
